---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/rhysd/actionlint
  rev: v1.7.1
  hooks:
  - id: actionlint
- repo: https://github.com/koalaman/shellcheck-precommit
  rev: v0.10.0
  hooks:
  - id: shellcheck
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: no-commit-to-branch
    args: [--branch, master]
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-yaml
  - id: check-xml
  - id: check-json
  - id: check-toml
  - id: check-symlinks
  - id: fix-byte-order-marker
